[package]
name = "niwoe-lock"
version.workspace = true
edition = "2021"

[[bin]]
name = "niwoe-lock"
path = "src/main.rs"

[[bin]]
name = "niwoe-openbsd-auth"
path = "src/bin/niwoe-openbsd-auth.rs"

[dependencies]
niwoe-config = { path = "../niwoe-config" }
niwoe-tokens = { path = "../niwoe-tokens" }
niwoe-ui = { path = "../niwoe-ui" }
libc = "0.2"
tiny-skia = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
xkbcommon = "0.8"
zeroize = "1"

[target.'cfg(not(target_os = "openbsd"))'.dependencies]
pam-sys = "1.0.0-alpha5"
