#!/usr/bin/env python3
"""Generate shipped theme tables from the canonical Rust Palette only.

No wallpaper, font, geometry or shared KDE/GTK configuration is written.
Run from any directory; --check verifies that generated artifacts are current.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def theme_text(name):
    source = (ROOT / "crates/niwoe-tokens/src/color.rs").read_text(encoding="utf-8")
    match = re.search(r"pub const " + name.upper() + r": Palette = Palette \{(.*?)\n    \};", source, re.S)
    if not match:
        raise ValueError(f"canonical palette {name} not found")
    colors = re.findall(r"(\w+): Color::rgb\(0x([0-9a-f]{2}), 0x([0-9a-f]{2}), 0x([0-9a-f]{2})\)", match[1])
    if len(colors) != 11:
        raise ValueError("Palette format changed; update generator before writing")
    lines = ["# Generated by scripts/gen-niwoe-theme.py from niwoe-tokens.",
             "# Edit the Rust palette, then regenerate. Geometry is shared.",
             "", "[colors]"]
    lines += [f'{role} = "#{r}{g}{b}"' for role, r, g, b in colors]
    lines += ["", "[icons]", 'theme = "Papirus"', ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name in ("dark", "light"):
        path = ROOT / "themes" / name / "theme.toml"
        expected = theme_text(name)
        if args.check:
            if path.read_text(encoding="utf-8") != expected:
                raise SystemExit(f"Out of date: {path}")
        else:
            path.write_text(expected, encoding="utf-8")
        print(f"OK: {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
