#!/usr/bin/env bash
#
# Regenerate the auto-generated symbol map inside docs/CODE_INDEX.md.
#
# The hand-written sections of CODE_INDEX.md (crate map, concern map) carry the
# "what does it do" knowledge and are NEVER touched by this script. This script
# only rewrites the region between the two GENERATED markers with a fresh
# per-crate listing of every top-level item (fn / struct / enum / trait / type /
# impl) and its file:line — so line numbers never go stale by hand.
#
# Usage:  scripts/gen_code_index.sh
# CI:     run it and `git diff --exit-code docs/CODE_INDEX.md` to fail if stale
#         (same spirit as the design_guard test).
#
# Portable: needs only bash, find, grep, awk, wc, sed (no ripgrep, no nightly).

# No pipefail: the `grep | sed | awk` listing pipelines intentionally tolerate a
# grep with zero matches and an early-closing limiter without aborting.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INDEX="$ROOT/docs/CODE_INDEX.md"
BEGIN="<!-- BEGIN GENERATED: symbol map — regenerate with scripts/gen_code_index.sh -->"
END="<!-- END GENERATED -->"

if [ ! -f "$INDEX" ]; then
  echo "error: $INDEX not found" >&2
  exit 1
fi

# Emit the markdown body of the generated region to stdout.
gen() {
  echo "_Generated by \`scripts/gen_code_index.sh\`. Do not edit by hand._"
  echo
  # Iterate crates alphabetically, then the root binary crate last.
  local dirs=()
  while IFS= read -r d; do dirs+=("$d"); done < <(find "$ROOT/crates" -maxdepth 1 -mindepth 1 -type d | sort)
  dirs+=("$ROOT")

  for crate_dir in "${dirs[@]}"; do
    local src="$crate_dir/src"
    [ -d "$src" ] || continue
    local crate
    if [ "$crate_dir" = "$ROOT" ]; then
      crate="niwoe (root binary)"
    else
      crate="$(basename "$crate_dir")"
    fi

    local files
    files="$(find "$src" -name '*.rs' | sort)"
    [ -n "$files" ] || continue

    echo "### \`$crate\`"
    echo

    while IFS= read -r f; do
      local rel lines
      rel="${f#"$ROOT"/}"
      lines="$(wc -l < "$f" | tr -d ' ')"
      echo "<details><summary><code>$rel</code> &mdash; ${lines} lines</summary>"
      echo
      echo '```rust'
      # Top-level items + impl blocks + any fn (methods included), with line no.
      grep -nE '^[[:space:]]*(pub(\([^)]*\))?[[:space:]]+)?(async[[:space:]]+)?(fn|struct|enum|trait|type)[[:space:]]|^[[:space:]]*impl[[:space:]]' "$f" \
        | sed -E 's/[[:space:]]*[\{\(].*$//; s/[[:space:]]+$//' \
        | awk 'NR<=300'
      echo '```'
      echo
      echo "</details>"
      echo
    done <<< "$files"
  done
}

tmp="$(mktemp)"
genfile="$(mktemp)"
gen > "$genfile"

awk -v b="$BEGIN" -v e="$END" -v gf="$genfile" '
  state==0 { print; if ($0==b) { print ""; while ((getline line < gf) > 0) print line; state=1 } next }
  state==1 { if ($0==e) { print ""; print; state=2 } next }
  state==2 { print }
' "$INDEX" > "$tmp"

if ! grep -qF "$BEGIN" "$INDEX"; then
  echo "error: BEGIN marker not found in $INDEX; nothing updated" >&2
  rm -f "$tmp" "$genfile"
  exit 1
fi

mv "$tmp" "$INDEX"
rm -f "$genfile"
echo "Updated $INDEX"
