//! Geometry and opacity tokens for the full-width native Control Center.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ControlCenter {
    pub sidebar_width: i32,
    pub header_height: i32,
    pub toolbar_height: i32,
    pub right_rail_width: i32,
    pub outer_pad: i32,
    pub card_gap: i32,
    pub card_pad: i32,
    pub room_config_button_width: i32,
    pub room_columns: i32,
    pub room_page_rows: i32,
    pub sidebar_item_height: i32,
    pub sidebar_section_gap: i32,
    pub filter_height: i32,
    pub filter_all_width: i32,
    pub filter_status_width: i32,
    pub filter_inactive_width: i32,
    pub filter_sort_width: i32,
    pub back_height: i32,
    pub status_dot_size: i32,
    pub quick_actions_height: i32,
    pub statistics_height: i32,
    pub config_tabs_height: i32,
    pub config_header_height: i32,
    pub config_footer_height: i32,
    pub config_details_height: i32,
    pub config_context_height: i32,
    pub config_lower_height: i32,
    pub config_preview_height: i32,
    pub config_note_height: i32,
    pub config_field_height: i32,
    pub config_action_width: i32,
    pub config_save_width: i32,
    pub card_window_rows: usize,
    pub content_alpha: u8,
    pub sidebar_alpha: u8,
    pub card_alpha: u8,
    pub header_tint_alpha: u8,
    pub disabled_alpha: u8,
}

impl ControlCenter {
    pub const DEFAULT: ControlCenter = ControlCenter {
        sidebar_width: 248,
        header_height: 192,
        toolbar_height: 72,
        right_rail_width: 286,
        outer_pad: 20,
        card_gap: 12,
        card_pad: 14,
        room_config_button_width: 146,
        room_columns: 3,
        room_page_rows: 3,
        sidebar_item_height: 48,
        sidebar_section_gap: 24,
        filter_height: 40,
        filter_all_width: 132,
        filter_status_width: 104,
        filter_inactive_width: 112,
        filter_sort_width: 128,
        back_height: 52,
        status_dot_size: 9,
        quick_actions_height: 196,
        statistics_height: 212,
        config_tabs_height: 56,
        config_header_height: 132,
        config_footer_height: 60,
        config_details_height: 180,
        config_context_height: 264,
        config_lower_height: 180,
        config_preview_height: 456,
        config_note_height: 182,
        config_field_height: 38,
        config_action_width: 142,
        config_save_width: 180,
        card_window_rows: 3,
        content_alpha: 246,
        sidebar_alpha: 236,
        card_alpha: 224,
        header_tint_alpha: 154,
        disabled_alpha: 104,
    };
}

impl Default for ControlCenter {
    fn default() -> Self {
        Self::DEFAULT
    }
}
