/// Geometry and translucent overlays for the Settings view hosted inside the
/// launcher surface. Settings shares the launcher's outer dimensions while
/// keeping its own, denser information hierarchy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Settings {
    pub header_height: i32,
    pub heading_height: i32,
    pub header_pad: i32,
    pub header_gap: i32,
    pub back_width: i32,
    pub search_width: i32,
    pub search_height: i32,
    pub sidebar_width: i32,
    pub sidebar_top_pad: i32,
    pub sidebar_content_pad: i32,
    pub sidebar_back_height: i32,
    pub sidebar_brand_height: i32,
    pub content_pad: i32,
    pub group_pad: i32,
    pub group_gap: i32,
    pub group_heading_height: i32,
    pub appearance_group_height: i32,
    pub option_gap: i32,
    pub theme_option_height: i32,
    pub theme_preview_width: i32,
    pub theme_preview_height: i32,
    pub display_identity_height: i32,
    pub display_mode_height: i32,
    pub display_control_height: i32,
    pub display_control_gap: i32,
    pub sidebar_row_height: i32,
    pub sidebar_section_height: i32,
    pub sidebar_group_gap: i32,
    pub sidebar_row_inset: i32,
    pub selection_inset: i32,
    pub selection_bar_width: i32,
    pub divider_size: i32,
    pub wallpaper_thumbnail_width: u32,
    pub wallpaper_thumbnail_height: u32,
    pub wallpaper_row_height: i32,
    pub wallpaper_browse_height: i32,
    pub wallpaper_grid_columns: usize,
    pub wallpaper_control_width: i32,
    pub cursor_row_height: i32,
    pub cursor_preview_side: i32,
    pub cursor_grid_columns: usize,
    pub cursor_size_width: i32,
    pub device_control_width: i32,
    pub volume_preset_width: i32,
    /// Internal settings cards are opaque like the archived reference.
    pub card_alpha: u8,
    /// Navigation-band opacity; Settings must not expose launcher blur.
    pub sidebar_alpha: u8,
    /// Search-field opacity on the opaque settings surface.
    pub search_alpha: u8,
    /// Hairline separator over `Palette::accent`.
    pub divider_alpha: u8,
}

impl Settings {
    pub const DEFAULT: Settings = Settings {
        header_height: 76,
        heading_height: 48,
        header_pad: 24,
        header_gap: 8,
        back_width: 40,
        search_width: 336,
        search_height: crate::Controls::FORM_HEIGHT,
        sidebar_width: 224,
        sidebar_top_pad: 8,
        sidebar_content_pad: 16,
        sidebar_back_height: 32,
        sidebar_brand_height: 48,
        content_pad: 32,
        group_pad: 24,
        group_gap: 16,
        group_heading_height: 56,
        appearance_group_height: 164,
        option_gap: 12,
        theme_option_height: 76,
        theme_preview_width: 64,
        theme_preview_height: 44,
        display_identity_height: 112,
        display_mode_height: 64,
        display_control_height: 64,
        display_control_gap: 8,
        sidebar_row_height: crate::Controls::MIN_HEIGHT,
        sidebar_section_height: 18,
        sidebar_group_gap: crate::Spacing::DEFAULT.xs,
        sidebar_row_inset: 8,
        selection_inset: 6,
        selection_bar_width: 3,
        divider_size: 1,
        wallpaper_thumbnail_width: 112,
        wallpaper_thumbnail_height: 63,
        wallpaper_row_height: 80,
        wallpaper_browse_height: 50,
        wallpaper_grid_columns: 2,
        wallpaper_control_width: 160,
        cursor_row_height: 64,
        cursor_preview_side: 48,
        cursor_grid_columns: 3,
        cursor_size_width: 160,
        device_control_width: 160,
        volume_preset_width: 104,
        card_alpha: 255,
        sidebar_alpha: 255,
        search_alpha: 255,
        divider_alpha: 44,
    };
}

impl Default for Settings {
    fn default() -> Self {
        Self::DEFAULT
    }
}
