NiwoeShell {
        registry_state: RegistryState::new(&globals),
        seat_state: SeatState::new(&globals, &qh),
        output_state: OutputState::new(&globals, &qh),
        shm,
        desktop_layer,
        desktop_menu_layer,
        panel,
        launcher_layer,
        calendar_layer,
        workspace_layer,
        network_layer,
        notification_layer,
        thumbnail_layer,
        desktop_configured: false,
        desktop_menu_configured: false,
        panel_configured: false,
        launcher_configured: false,
        calendar_configured: false,
        workspace_configured: false,
        network_configured: false,
        notification_configured: false,
        thumbnail_configured: false,
        thumbnail_popup_open: false,
        desktop_menu_open: false,
        desktop_menu_opened_at: None,
        consent_layer,
        consent_configured: false,
        consent_buffer: None,
        consent_open: false,
        consent_request_id: None,
        consent_app_id: String::new(),
        consent_hover: None,
        wifi_modal_layer,
        wifi_modal_configured: false,
        wifi_modal_buffer: None,
        wifi_modal_open: false,
        wifi_modal_hover: None,
        region_picker_layer,
        region_picker_configured: false,
        region_picker_buffer: None,
        region_picker_open: false,
        region_picker_request_id: None,
        region_picker_app_id: String::new(),
        region_picker_local: false,
        region_picker_width: 0,
        region_picker_height: 0,
        region_picker_drag_start: None,
        region_picker_drag_current: None,
        region_picker_pending: None,
        default_apps_index: None,
        default_apps_current: std::collections::HashMap::new(),
        default_apps_picker_open: None,
        default_apps_page: 0,
        default_apps_status: crate::default_apps::refresh::UiState::default(),
        audio_popup_open: false,
        audio_volume_dragging: false,
        quick_settings_volume_pending: None,
        volume_osd_open: false,
        volume_osd_pending: false,
        volume_osd_hide_at: None,
        volume_osd_width: 0,
        volume_osd_height: 0,
        osd_power_profile: None,
        panel_buffer: None,
        desktop_menu_buffer: None,
        launcher_buffer: None,
        calendar_buffer: None,
        workspace_buffer: None,
        network_buffer: None,
        notification_buffer: None,
        thumbnail_buffer: None,
        pool,
        width: 1024,
        desktop_width: 1024,
        desktop_height: 768,
        desktop_menu_width: crate::context_menu::MENU_WIDTH as u32,
        desktop_menu_height: 1,
        launcher_width: LAUNCHER_WIDTH,
        launcher_height: LAUNCHER_HEIGHT,
        launcher_is_fullscreen: false,
        launcher_visual_x: 8,
        launcher_visual_y: 0,
        calendar_width: crate::popup_surface_w(CALENDAR_POPUP_WIDTH),
        calendar_height: crate::popup_surface_h(CALENDAR_POPUP_HEIGHT),
        workspace_width: crate::popup_surface_w(WORKSPACE_POPUP_WIDTH),
        workspace_height: crate::popup_surface_h(WORKSPACE_POPUP_HEIGHT),
        network_width: crate::popup_surface_w(NETWORK_POPUP_WIDTH),
        network_height: crate::popup_surface_h(NETWORK_POPUP_HEIGHT),
        audio_width: crate::popup_surface_w(AUDIO_POPUP_WIDTH),
        audio_height: crate::popup_surface_h(AUDIO_POPUP_HEIGHT),
        status_notifier_menu_width: crate::status_notifier_popup::SNI_MENU_WIDTH,
        status_notifier_menu_height: 1,
        notification_width: crate::popup_surface_w(crate::NOTIFICATION_WIDTH),
        notification_height: crate::popup_surface_h(crate::NOTIFICATION_HEIGHT),
        thumbnail_width: 0,
        thumbnail_height: 0,
        thumbnail_dirty: false,
        thumbnail_hover_app_idx: None,
        thumbnail_hover_since: None,
        thumbnail_popup_window_ids: Vec::new(),
        thumbnail_cache: std::collections::HashMap::new(),
        thumbnail_icon_center: None,
        armed_power: None,
        notifications: std::collections::VecDeque::new(),
        notification_dirty: false,
        status_notifier_items: Vec::new(),
        status_notifier_tx: None,
        status_notifier_menu: None,
        status_notifier_menu_open: false,
        status_notifier_menu_entries: Vec::new(),
        settings_category: crate::settings_view::SettingsCategory::default(),
        settings_pinned_adding: false,
        system_info,
        user_accounts: Default::default(),
        settings_refresh_tx,
        settings_refresh_rx,
        settings_refresh_inflight: std::collections::HashSet::new(),
        printer_snapshot,
        audio_snapshot,
        deck_mutation: Default::default(),
        audio_settled,
        audio_poll_until: std::time::Instant::now() + std::time::Duration::from_secs(60),
        battery_snapshot: crate::battery::BatterySnapshot::poll(),
        power_profile: power_profile_init,
        launcher_icons_warmed: false,
        keyboard: None,
        keyboard_focus: SurfaceKind::None,
        pointer: None,
        pointer_position: (0.0, 0.0),
        pointer_surface: SurfaceKind::None,
        available_themes,
        theme_name: theme_manager.current().name.clone(),
        available_wallpapers,
        wallpaper_thumbnails: Vec::new(),
        wallpaper_page: 0,
        wallpaper_picker_rx: None,
        wallpaper_path: niwoe_config.wallpaper.as_ref().map(|w| w.path.clone()),
        wallpaper_mode: niwoe_config
            .wallpaper
            .as_ref()
            .map(|w| w.mode)
            .unwrap_or_default(),
        cursor_size: niwoe_config
            .cursor
            .as_ref()
            .map(|c| c.size)
            .unwrap_or_else(|| niwoe_config::CursorConfig::default().size),
        cursor_previews: crate::cursor::preview::CursorPreviews::default(),
        available_cursor_themes: crate::cursor::scan_cursor_themes(),
        cursor_theme: crate::cursor::current_cursor_theme(),
        idle_timeout_secs: niwoe_config.general.idle_timeout_secs,
        theme,
        font: RefCell::new(font),
        icon_cache,
        network_controller,
        network_profiles,
        network_list_status: crate::network::ListStatus::default(),
        wifi_networks: Vec::new(),
        wifi_password_prompt: None,
        wifi_password_input: String::new(),
        network_popup_tab: crate::network_popup::NetworkTab::Status,
        bluetooth_snapshot: crate::bluetooth::BluetoothSnapshot::default(),
        ipc: ipc_client,
        panel_state: panel::PanelState::new(),
        pinned_apps,
        launcher_state: launcher::LauncherState::new_with_apps(launcher_apps),
        launcher_apps_rx: None,
        launcher_icons_rx: None,
        workspace_state: crate::workspaces::WorkspacePopupState::new(),
        workspace_hover_idx: None,
        focused_window_id: None,
        focused_title: None,
        windows: Vec::new(),
        active_workspace: 0,
        focused_output_id: None,
        output_workspaces: Vec::new(),
        output_workspace_state_available: false,
        display_mode_dropdown_open: None,
        display_pages: crate::settings_view::DisplayPages::default(),
        provider_page: 0,
        workspace_window_counts: [0; niwoe_config::rooms::MAX_ROOMS],
        occupied_workspaces: [false; niwoe_config::rooms::MAX_ROOMS],
        occupied_state_available: false,
        workspace_state_received: false,
        workspace_indicator_dirty: true,
        workspace_ipc_unavailable_logged: false,
        occupied_unavailable_logged: false,
        panel_dirty: true,
        launcher_dirty: true,
        ui_preview_widget_state: None,
        panel_widget_state: None,
        launcher_selected_idx: None,
        hovered_bento_idx: None,
        room_keyboard_focus: None,
        settings_hovered: false,
        hovered_power_btn: None,
        hovered_app_card_idx: None,
        app_view_scroll_y: 0,
        launcher_scroll_remainder: 0.0,
        launcher_settings_open: false,
        settings_return_to_room_management: false,
        control_center_nav: Default::default(),
        room_management_open: false,
        room_management_page: 0,
        room_configuration_id: None,
        room_configuration_scroll_y: 0,
        room_configuration_save_pending: false,
        context_menu: None,
        desktop_context_menu: None,
        hidden_execs: crate::wayland::state::load_hidden_apps(),
        search_query: String::new(),
        hub_search_active: false,
        hub: Default::default(),
        window_picker: None,
        settings_search: String::new(),
        calendar_dirty: true,
        workspace_dirty: true,
        network_dirty: true,
        audio_dirty: true,
        calendar_popup_open: false,
        workspace_popup_open: false,
        network_popup_open: false,
        calendar_display_policy: CalendarDisplayPolicy::default(),
        panel_last_signature: None,
        panel_preview: Default::default(),
        panel_click_zones_snapshot: None,
        repaint_stats: Default::default(),
        repaint_stats_enabled: flags::enabled("NIWOE_SHELL_REPAINT_STATS"),
        last_repaint_stats_log: Instant::now(),
        commit_stats: CommitStats::default(),
        commit_stats_enabled,
        last_commit_stats_log: Instant::now(),
        render_stats: Default::default(),
        render_stats_enabled,
        last_render_stats_log: Instant::now(),
        commit_info_until: Instant::now()
            + if commit_stats_enabled {
                std::time::Duration::from_secs(5)
            } else {
                std::time::Duration::ZERO
            },
        last_clock: String::new(),
        last_tick: Instant::now(),
        exit: false,
        screencopy_manager,
        capture_source_manager,
        screenshot_capture: None,
    }
